create table worktimes (
  id SERIAL NOT NULL,
  day_id INT NOT NULL,
  store_id INT NOT NULL,
  am_open VARCHAR(5),
  am_close VARCHAR(5),
  pm_open VARCHAR(5),
  pm_close VARCHAR(5),
  CONSTRAINT day_shop UNIQUE (day_id, store_id),
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  PRIMARY KEY (id)
);

INSERT INTO categories (name) VALUES ('austrail');
INSERT INTO categories (name) VALUES ('assujeterrogée');
INSERT INTO categories (name) VALUES ('recycloît');
INSERT INTO categories (name) VALUES ('habille');
INSERT INTO categories (name) VALUES ('écanus');
INSERT INTO categories (name) VALUES ('vissance');
INSERT INTO categories (name) VALUES ('cons');
INSERT INTO categories (name) VALUES ('écotes');
INSERT INTO categories (name) VALUES ('nationaliszt');
INSERT INTO categories (name) VALUES ('connée');
INSERT INTO categories (name) VALUES ('camérenventale');
INSERT INTO categories (name) VALUES ('alifiquipe');
INSERT INTO categories (name) VALUES ('décidents');
INSERT INTO categories (name) VALUES ('frassionson');
INSERT INTO categories (name) VALUES ('tration');
insert into stores (name, is_holiday) values ('bentionnaire', false);
insert into stores (name, is_holiday) values ('évélémenté', false);
insert into stores (name, is_holiday) values ('cécis', true);
insert into stores (name, is_holiday) values ('mulevé', false);
insert into stores (name, is_holiday) values ('tracessemart', false);
insert into stores (name, is_holiday) values ('filon', true);
insert into stores (name, is_holiday) values ('plume', false);
insert into stores (name, is_holiday) values ('rasser', false);
insert into stores (name, is_holiday) values ('cons', false);
insert into stores (name, is_holiday) values ('assuspensistan', false);
insert into stores (name, is_holiday) values ('blatigation', true);
insert into stores (name, is_holiday) values ('désinki', false);
insert into stores (name, is_holiday) values ('diseur', false);
insert into stores (name, is_holiday) values ('nathanne', true);
insert into stores (name, is_holiday) values ('cale', true);
insert into stores (name, is_holiday) values ('ins', false);
insert into stores (name, is_holiday) values ('intes', false);
insert into stores (name, is_holiday) values ('tuente', false);
insert into stores (name, is_holiday) values ('touffer', false);
insert into stores (name, is_holiday) values ('hélinstaul', false);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mexigue', 'ges', 'panées', 'cer', '44.66219', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('écoméditique', 'crochampue', 'ajouversembaucunien', 'tuber', '104.68662', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('estasme', 'trarieux', 'déplusina', 'sacroyer', '28.467579', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('lisme', 'décontréen', 'pathisseur', 'métat', '124.65137', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('fume', 'effeuillemenoncreux', 'vogent', 'devientambitué', '83.67214', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('dra', 'instavendelettelandaissassac', 'monissoir', 'syndin', '79.48104', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('discaincongement', 'soublion', 'défier', 'bles', '25.054422', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('galabouilli', 'toumérontraler', 'faroducartisant', 'avation', '332.5399', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('edgarrière', 'accuerait', 'basque', 'amiquettaillacée', '368.96906', 4);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('retageant', 'gadopte', 'attrivitique', 'mayantark', '122.725525', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('jaugustant', 'michermé', 'turetrop', 'graments', '427.3524', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('barrière', 'discrités', 'artellanterménarcher', 'jacqué', '206.68137', 4);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('vale', 'hexacte', 'justeronique', 'rant', '217.36322', 15);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('valuer', 'tens', 'plusinime', 'glandernit', '106.661', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('biens', 'prévers', 'solencer', 'ble', '366.7134', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('manalistremède', 'souhaits', 'mécrabler', 'nécesses', '317.4116', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('iroposés', 'carticot', 'station', 'nouvementuelleurs', '429.43738', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('lisés', 'parale', 'récons', 'argés', '182.04767', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('jésulties', 'taxis', 'bossentairvoyé', 'ennent', '91.364204', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('redet', 'rectifié', 'ber', 'collagenégauché', '124.99174', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('de', 'brûlée', 'repréalisseux', 'lucie', '236.24979', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('deveux', 'insticitesquipatchée', 'remon', 'liste', '266.8447', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('joute', 'anté', 'dévaciat', 'sappartraume', '420.92047', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('assonalysme', 'correau', 'accordésaccordé', 'dévalution', '316.28857', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('sités', 'ble', 'sous-vertermi', 'proc', '241.43204', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('équipétorquanimulgameletit', 'chois', 'légot', 'baniciteurs', '77.19127', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('gasinée', 'gran', 'michettes', 'res', '34.189186', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('choire', 'menée', 'flame', 'répulevée', '407.26834', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('amste', 'enfluxelluleverti', 'hiéraphe', 'venue', '361.92258', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('magistosh', 'crationner', 'patrifie', 'hormandifier', '483.84097', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('contentinance', 'situde', 'élé', 'célèvestes', '487.62744', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ent', 'opend', 'unitzle', 'emplicalophère', '325.90707', 17);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('hélibéré', 'ner', 'conces', 'payées', '139.23297', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('jague', 'étaillattages', 'visé', 'rement', '418.595', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('coups', 'ennel', 'portageste', 'marmédit', '354.76672', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('platérallarc', 'accrue', 'arge', 'coifférent', '413.34454', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mobile', 'enfortis', 'grâce', 'démouse', '70.25276', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('parenant', 'cation', 'ent', 'digaresselle', '33.071987', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('reçut', 'cas', 'juif', 'angorie', '267.77765', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('expédie', 'aries', 'recrue', 'sénagement', '75.45055', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('pro', 'onormateur', 'rénomique', 'diste', '189.47894', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('colligatier', 'doucer', 'démande', 'décontrer', '346.72275', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('osc', 'prognanter', 'supplie', 'réger', '25.186184', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('secontir', 'déses', 'assisseauxquis', 'déranchinergeurer', '105.496574', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('souddhi', 'tâter', 'minité', 'courque', '122.932594', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('infrony', 'touteur', 'lice', 'carappliateursuant', '370.96246', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('iniquent', 'prespiluvi', 'bronomissandtlanculiques', 'destique', '387.32288', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('nouinencer', 'musicaustif', 'taxer', 'cande', '438.75403', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('regarespers', 'tran', 'vibre', 'peiné', '162.10393', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('boule', 'soiser', 'opérial', 'occurrage', '407.03122', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('dévêque', 'morterdité', 'enser', 'réfréquement', '460.94122', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('déjeux', 'propogravaitable', 'dé', 'tar', '234.72856', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('indre', 'jalombation', 'rééchambigambine', 'culairecoméricot', '469.60864', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('vacule', 'intérobe', 'casie', 'réface', '242.53561', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('cessigner', 'écharchirées', 'foise', 'helime', '151.24796', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('emparée', 'patribercevarder', 'lairiel', 'person', '55.19278', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('orgie', 'réfugiransion', 'fossel', 'escomples', '424.8357', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('crois', 'sourginiqué', 'collais', 'équins', '196.44522', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('pouille', 'liaissement', 'évité', 'barythme', '349.261', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('expédait', 'adverrogratifs', 'sent', 'impendustris', '264.84235', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('méthiopiquent', 'motin', 'gazarritalifichercés', 'hures', '196.81677', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('hypestiplômeuse', 'injuge', 'marques', 'autoransposanthe', '251.30525', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('iodifféral', 'res', 'oure', 'fligiersiflateur', '144.36876', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('phostupi', 'mon', 'débatation', 'laritairemois', '315.79556', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('fixe', 'émandans', 'thousse', 'submerc', '28.028755', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('quaraînée', 'indic', 'errer', 'embandaime', '279.8524', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('succent', 'déments', 'proverts', 'délande', '140.45659', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('torice', 'mous', 'déplacretienne', 'vêtement', '17.20068', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('intentôt', 'sementé', 'sortisés', 'prochésigne', '456.5946', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('permicroidir', 'blavainstalognement', 'ter', 'affamangs', '16.379007', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('couilliersion', 'versistes', 'tistétiqués', 'porte-en-jamication', '65.30191', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ancellegment', 'rections', 'réussium', 'bavure', '185.54826', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('recturend', 'thés', 'passe', 'faix', '334.78278', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('rire', 'ent', 'torio', 'talités', '430.83582', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('grisages', 'abats', 'durinerves', 'crépartes', '172.2409', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('expose', 'heur', 'cons', 'inseille', '260.6389', 4);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('cont', 'stranse', 'inoire', 'révolière', '322.7682', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('rendais', 'hortenté', 'parfaible', 'socio-écontalité', '90.55966', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('montouflemenégaux', 'convénier', 'jeur', 'ent', '89.07753', 17);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('rouvre', 'présignergot', 'irreux', 'puniste', '200.49458', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('consécute', 'wagonde', 'noun', 'sovident', '444.03003', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('vés', 'amillité', 'reliennement', 'lance', '80.109085', 18);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('bordaigu', 'oublique', 'ski', 'gilencelles', '324.3632', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('dateur', 'vulgarder', 'frivant', 'hériphérateurs', '203.45082', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('sûrs', 'discits', 'musé', 'démotique', '404.32828', 15);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('dérément', 'communaux', 'glo', 'tbilité', '235.02849', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('chiat', 'marquanité', 'dre', 'wagonsœuvre', '473.88208', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('sommobigle', 'perfétaler', 'laiser', 'ins', '141.99625', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('diviles', 'modestinution', 'interne', 'sommentérir', '209.07024', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('contré', 'mointés', 'soute', 'amilité', '82.64442', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('égligin', 'raphilars', 'hériques', 'concer', '335.2598', 4);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('créments', 'guissant', 'choquait', 'précourbandantine', '34.41517', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('textorovertis', 'sonnait', 'metter', 'rivale', '237.76453', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('bigne', 'recumulées', 'accompère', 'domprudiés', '203.46362', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('non-int', 'enjamer', 'voir', 'transforêt', '181.05997', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('va', 'saccélévatribliagote', 'courisquarterictorté', 'phalter', '84.037025', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('vole', 'khme', 'gêné', 'trariables', '112.24425', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('redoutent', 'rément', 'jus', 'doireculaisement', '468.2874', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('réalisir', 'jaunie', 'youge', 'vialectionnel', '481.33322', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('inguer', 'souver', 'produit', 'accueilliste', '74.04942', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('comphone', 'discole', 'intimer', 'obtienté', '149.41539', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('agrais', 'alphagrattait', 'tassait', 'augementaire', '273.72568', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ant', 'boucher', 'inhabraguer', 'droiement', '11.1897955', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ventin-pêchen', 'yanter', 'rustithéodoxalto', 'désumérait', '200.56424', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('compe', 'noyellectivainque', 'offrone', 'pesaiserronaire', '204.46992', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('élevagulaisens', 'guettez', 'faiteau', 'péridit', '177.28152', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('blêmemencent', 'courasserierge', 'pine', 'néant', '362.7046', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('toir', 'figue', 'frôlé', 'mas', '58.017086', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('contage', 'secrutefeu', 'sennellée', 'don', '289.71774', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ser', 'camontée', 'cons', 'hugonal', '322.56976', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('maroque', 'inquêtes', 'gar', 'fêle', '133.26646', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('verremployé', 'âprespections', 'mélodz', 'nippelle', '38.682297', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('éros', 'cotes', 'carbit', 'orien', '25.58307', 18);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('stan', 'sac', 'travé', 'cation', '167.30307', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('boule', 'crés', 'dos', 'route', '426.43762', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('garia', 'grèvement', 'mozarder', 'rapher', '39.715443', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('enser', 'mentés', 'nuit', 'prons', '108.54628', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('admir', 'malaye', 'emplément', 'frimeuser', '460.84418', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('pération', 'côté', 'plance', 'étony', '162.66803', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('égle', 'clu', 'fard', 'plant', '132.75435', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('toura', 'dir', 'disse', 'pigerient', '43.061317', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ment', 'dignés', 'éblocailly', 'cle', '399.0073', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mes', 'res', 'voulipse', 'peaux', '291.5409', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('géant', 'venu', 'taxation', 'sités', '348.37756', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('soire', 'friginancient', 'villement', 'étones', '215.04852', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('tens', 'belle', 'empident', 'rents', '494.79163', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('apeau', 'dépentisser', 'venacement', 'audes', '240.3277', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('natifs', 'rappliszt', 'cler', 'emmerge', '198.70448', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('fraient', 'condanogrer', 'marraientraringuer', 'écrifères', '476.25735', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('firmellement', 'bonné', 'irrivernites', 'annuits', '263.6603', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ver', 'sorts', 'rétageure', 'bure', '427.75803', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('venié', 'préventrée', 'inauté', 'parter', '395.80542', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('combre', 'hexactuelle', 'inconjoue', 'hormate', '277.30075', 17);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('barculez', 'syndic', 'assemble', 'décont', '230.90616', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('évêtir', 'actue', 'bientégriner', 'préviaire', '402.56287', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('compartisantatis', 'termédition', 'ukrains', 'procalme', '141.34178', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('repôt', 'diplets', 'dur', 'égatorquise', '291.55365', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('incoupés', 'natoirer', 'meublinguie', 'cycle', '11.048339', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('patial', 'corcéreuse', 'urnois', 'palme', '33.72746', 1);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('impoologie', 'démie', 'unistations', 'mayage', '57.708595', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('meur', 'sommet', 'charastique', 'disse', '20.313553', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('moubouchernisé', 'hération', 'coutait', 'office', '424.84943', 18);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('persévélecturé', 'suppréhard', 'inté', 'renant', '471.30612', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('exténorer', 'préciscrution', 'évapossinent', 'joël', '107.82894', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('craquinement', 'vite', 'laïti', 'mère', '12.118839', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('traler', 'détent', 'oppos', 'condouchevasée', '276.0148', 15);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('jouillus', 'élonda', 'calcoopé', 'ent', '221.50151', 9);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('musion', 'misse', 'quant', 'parfain', '252.69334', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('paienner', 'troversongourie', 'maire', 'opéricouvainer', '298.65363', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('dégât', 'aigurancien', 'requer', 'païenner', '186.25151', 8);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('conctuels', 'demnis', 'subitrarce', 'combée', '209.09273', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('échaiter', 'conde', 'ille-clé', 'fonchanorde', '173.05365', 18);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('navisition', 'vendre', 'inant', 'figura', '167.05591', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('somme', 'couvés', 'appelé', 'inction', '339.6836', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('civistes', 'fossitifs', 'abonatuit', 'azon', '262.48044', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('anients', 'gazimbe', 'ins', 'cible', '362.71207', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('suffliginer', 'emmeille', 'hel', 'eries', '92.983635', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('che', 'escot', 'drait', 'ulcéré', '104.43321', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('balaider', 'fonne', 'croit', 'octer', '15.943693', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('moléré', 'sommentière', 'bloussemblements', 'aude', '8.643819', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('choute', 'porté', 'pourales', 'de', '22.288528', 4);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('nigrammesurvend', 'aution', 'vissin', 'traîchet', '378.5104', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('tsincarrans', 'lité', 'décitos', 'vient', '173.11522', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('super', 'constanisme', 'morphorièvre', 'chandistrait', '446.34003', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('res', 'demante', 'futiques', 'intés', '222.26143', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('écriabler', 'fanglement', 'puérandidenter', 'cédent', '244.58119', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('don', 'peladieurion', 'pivoriage', 'délangoulaté', '338.11615', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('en', 'veuf', 'infordam', 'lié', '278.8732', 14);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('laques', 'greb', 'exclu', 'courger', '385.86035', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mangs', 'infide', 'mots', 'kenal', '134.96364', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('flegment', 'arbère', 'expatiqué', 'survir', '200.60326', 5);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('jet', 'revent', 'poui', 'palent', '305.57965', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('longer', 'fédé', 'acteau-de-vitationalescaine', 'pavile', '334.27072', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('luder', 'isser', 'totant', 'finie', '475.49854', 18);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('prés', 'teligée', 'servant', 'rebarbordure', '477.8148', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('danglisée', 'cors', 'repterménagreu', 'innoncé', '282.3287', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('instement', 'omie', 'prentrépres', 'claises', '126.52849', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('armon', 'crée', 'même', 'commaignantin', '315.01904', 12);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('repost', 'exclubrié', 'dûment', 'croche', '444.66046', NULL);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('angement', 'cossion', 'clargnéer', 'bré', '415.02542', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('rendusté', 'èvementaris', 'lance', 'détoilend', '253.03378', 7);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('estravaurès', 'supplais', 'polidard', 'cordivons', '263.64966', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('vipède', 'instables', 'plir', 'glaces', '159.16766', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('censeignantion', 'mage', 'sauvrion', 'infection', '149.08125', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('convaritorque', 'terressent', 'désings', 'compressin', '421.0312', 2);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('als', 'travidue', 'repréver', 'alle', '80.35518', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('ager', 'remence', 'fédération', 'remi-dison', '372.49393', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('maté', 'reto', 'élus', 'polypseurs', '11.797975', 19);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('divençaisse', 'accoursement', 'archaîner', 'eth', '53.575073', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('birmettribustrammandent', 'impartonsitique', 'sociatieux', 'aimat', '448.13785', 3);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('amorcelle', 'vivorie', 'mystérer', 'instassif', '11.186286', 16);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('nigment', 'poire', 'pravalmer', 'formelon', '209.05215', 6);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mode', 'dif', 'éla', 'hinoir', '134.02644', 15);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('goulogie', 'otatiganspectivement', 'nettravanses', 'prennes', '1.1477023', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('canal', 'temensacréologitive', 'naïadavité', 'distipleur', '480.4261', 13);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('molé', 'entre', 'rent', 'national', '217.46465', 11);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('mente', 'offrer', 'traiser', 'alprofesse', '445.9776', 10);
INSERT INTO products (name, description, i18n_name, i18n_description, price, store_id) VALUES ('pinant', 'taphterverge', 'aprimidiques', 'secretrouscrer', '101.59433', 2);
INSERT INTO products_categories (product_id, category_id) VALUES (104, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (79, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (119, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (80, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (108, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (79, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (17, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (75, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (128, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (169, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (72, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (77, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (5, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (193, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (7, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (179, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (111, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (181, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (161, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (159, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (18, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (143, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (80, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (108, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (39, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (56, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (82, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (54, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (26, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (15, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (129, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (136, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (183, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (6, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (59, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (154, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (110, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (62, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (59, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (124, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (132, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (56, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (45, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (112, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (74, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (52, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (119, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (19, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (51, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (95, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (43, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (142, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (46, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (32, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (97, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (142, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (181, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (156, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (81, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (185, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (74, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (17, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (77, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (84, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (8, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (60, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (124, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (162, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (172, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (173, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (185, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (138, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (128, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (127, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (104, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (6, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (62, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (167, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (16, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (145, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (60, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (71, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (114, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (15, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (41, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (64, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (132, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (66, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (167, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (159, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (46, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (57, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (118, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (20, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (179, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (90, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (19, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (136, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (103, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (187, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (125, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (117, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (35, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (70, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (27, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (58, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (89, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (194, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (67, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (39, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (124, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (161, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (28, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (155, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (10, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (18, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (176, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (13, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (39, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (54, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (122, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (188, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (2, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (182, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (134, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (176, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (141, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (6, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (176, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (18, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (163, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (3, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (115, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (14, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (86, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (172, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (181, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (146, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (155, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (37, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (125, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (128, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (49, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (128, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (48, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (95, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (189, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (49, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (135, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (116, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (127, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (58, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (41, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (172, 6);
INSERT INTO products_categories (product_id, category_id) VALUES (19, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (174, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (115, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (54, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (63, 13);
INSERT INTO products_categories (product_id, category_id) VALUES (92, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (16, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (147, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (45, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (72, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (89, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (35, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (54, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (107, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (26, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (91, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (103, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (173, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (34, 2);
INSERT INTO products_categories (product_id, category_id) VALUES (133, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (183, 12);
INSERT INTO products_categories (product_id, category_id) VALUES (177, 5);
INSERT INTO products_categories (product_id, category_id) VALUES (175, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (135, 9);
INSERT INTO products_categories (product_id, category_id) VALUES (61, 14);
INSERT INTO products_categories (product_id, category_id) VALUES (40, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (60, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (151, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (9, 3);
INSERT INTO products_categories (product_id, category_id) VALUES (56, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (158, 11);
INSERT INTO products_categories (product_id, category_id) VALUES (94, 8);
INSERT INTO products_categories (product_id, category_id) VALUES (167, 10);
INSERT INTO products_categories (product_id, category_id) VALUES (103, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (187, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (10, 1);
INSERT INTO products_categories (product_id, category_id) VALUES (93, 7);
INSERT INTO products_categories (product_id, category_id) VALUES (157, 4);
INSERT INTO products_categories (product_id, category_id) VALUES (42, 6);
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 1, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 1, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 1, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 1, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 1, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 2, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 2, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 2, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 2, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 2, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 3, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 3, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 3, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 3, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 3, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 4, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 4, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 4, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 4, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 4, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 5, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 5, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 5, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 5, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 5, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 6, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 6, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 6, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 6, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 6, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 7, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 7, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 7, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 7, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 7, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 8, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 8, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 8, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 8, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 8, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 9, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 9, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 9, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 9, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 9, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 10, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 10, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 10, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 10, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 10, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 11, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 11, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 11, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 11, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 11, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 12, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 12, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 12, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 12, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 12, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 13, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 13, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 13, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 13, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 13, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 14, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 14, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 14, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 14, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 14, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 15, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 15, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 15, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 15, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 15, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 16, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 16, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 16, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 16, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 16, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 17, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 17, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 17, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 17, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 17, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 18, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 18, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 18, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 18, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 18, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 19, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 19, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 19, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 19, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 19, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (1, 20, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (2, 20, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (3, 20, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (4, 20, '08:00', '12:00', '02:00', '06:30');
INSERT INTO worktimes (day_id, store_id, am_open, am_close, pm_open, pm_close) VALUES (5, 20, '08:00', '12:00', '02:00', '06:30');
INSERT INTO products_categories (product_id, category_id) VALUES (101, 9);
